Add new region Mumbai
* add new region due to the official announcement
  https://aws.amazon.com/about-aws/whats-new/2016/06/announcing-the-aws-asia-pacific-mumbai-region/

* expand gitignore to skip file generated by marcelor/fabric-bash-autocompletion
* expand gitingore to skip file used by kennethreitz/autoenv

* known issue - certain RDS data generates errors, for example
  ERROR: Trouble generating reserved price: KeyError('yrTerm3.partialUpfront-quantity',)